import type {
  PantryItem,
  Recipe,
  Notification,
  BudgetStats,
  UserProfile,
} from './types'

const today = new Date()
const daysFromNow = (n: number) => {
  const d = new Date(today)
  d.setDate(d.getDate() + n)
  return d.toISOString().split('T')[0]
}
const daysAgo = (n: number) => daysFromNow(-n)

export const mockPantryItems: PantryItem[] = [
  {
    id: 'p1',
    name: 'Whole Milk',
    category: 'dairy',
    quantity: 1,
    unit: 'L',
    expirationDate: daysFromNow(2),
    location: 'fridge',
    urgency: 'expiring',
    addedDate: daysAgo(5),
  },
  {
    id: 'p2',
    name: 'Cherry Tomatoes',
    category: 'produce',
    quantity: 400,
    unit: 'g',
    expirationDate: daysFromNow(3),
    location: 'fridge',
    urgency: 'expiring',
    addedDate: daysAgo(4),
  },
  {
    id: 'p3',
    name: 'Free-Range Eggs',
    category: 'dairy',
    quantity: 8,
    unit: 'pcs',
    expirationDate: daysFromNow(12),
    location: 'fridge',
    urgency: 'fresh',
    addedDate: daysAgo(2),
  },
  {
    id: 'p4',
    name: 'Arborio Rice',
    category: 'grains',
    quantity: 500,
    unit: 'g',
    expirationDate: daysFromNow(180),
    location: 'pantry',
    urgency: 'fresh',
    addedDate: daysAgo(14),
  },
  {
    id: 'p5',
    name: 'Unsalted Butter',
    category: 'dairy',
    quantity: 250,
    unit: 'g',
    expirationDate: daysFromNow(20),
    location: 'fridge',
    urgency: 'fresh',
    addedDate: daysAgo(3),
  },
  {
    id: 'p6',
    name: 'Baby Spinach',
    category: 'produce',
    quantity: 200,
    unit: 'g',
    expirationDate: daysFromNow(-1),
    location: 'fridge',
    urgency: 'expired',
    addedDate: daysAgo(7),
  },
  {
    id: 'p7',
    name: 'Parmesan Cheese',
    category: 'dairy',
    quantity: 150,
    unit: 'g',
    expirationDate: daysFromNow(30),
    location: 'fridge',
    urgency: 'fresh',
    addedDate: daysAgo(1),
  },
  {
    id: 'p8',
    name: 'Garlic',
    category: 'produce',
    quantity: 4,
    unit: 'cloves',
    expirationDate: daysFromNow(60),
    location: 'pantry',
    urgency: 'fresh',
    addedDate: daysAgo(7),
  },
  {
    id: 'p9',
    name: 'Chicken Breast',
    category: 'meat',
    quantity: 600,
    unit: 'g',
    expirationDate: daysFromNow(2),
    location: 'fridge',
    urgency: 'expiring',
    addedDate: daysAgo(2),
  },
  {
    id: 'p10',
    name: 'Vegetable Stock',
    category: 'canned',
    quantity: 500,
    unit: 'ml',
    expirationDate: daysFromNow(120),
    location: 'pantry',
    urgency: 'fresh',
    addedDate: daysAgo(10),
  },
  {
    id: 'p11',
    name: 'Kalamata Olives',
    category: 'condiments',
    quantity: 200,
    unit: 'g',
    expirationDate: daysFromNow(3),
    location: 'fridge',
    urgency: 'expiring',
    addedDate: daysAgo(8),
  },
  {
    id: 'p12',
    name: 'All-Purpose Flour',
    category: 'grains',
    quantity: 1,
    unit: 'kg',
    expirationDate: daysFromNow(200),
    location: 'pantry',
    urgency: 'fresh',
    addedDate: daysAgo(20),
  },
  {
    id: 'p13',
    name: 'Greek Yoghurt',
    category: 'dairy',
    quantity: 500,
    unit: 'g',
    expirationDate: daysFromNow(7),
    location: 'fridge',
    urgency: 'fresh',
    addedDate: daysAgo(1),
  },
  {
    id: 'p14',
    name: 'Salmon Fillet',
    category: 'seafood',
    quantity: 400,
    unit: 'g',
    expirationDate: daysFromNow(1),
    location: 'fridge',
    urgency: 'expiring',
    addedDate: daysAgo(1),
  },
  {
    id: 'p15',
    name: 'Lemon',
    category: 'produce',
    quantity: 3,
    unit: 'pcs',
    expirationDate: daysFromNow(14),
    location: 'fridge',
    urgency: 'fresh',
    addedDate: daysAgo(3),
  },
  {
    id: 'p16',
    name: 'Frozen Peas',
    category: 'frozen',
    quantity: 400,
    unit: 'g',
    expirationDate: daysFromNow(90),
    location: 'freezer',
    urgency: 'fresh',
    addedDate: daysAgo(30),
  },
  {
    id: 'p17',
    name: 'Sourdough Bread',
    category: 'grains',
    quantity: 1,
    unit: 'loaf',
    expirationDate: daysFromNow(-2),
    location: 'pantry',
    urgency: 'expired',
    addedDate: daysAgo(5),
  },
  {
    id: 'p18',
    name: 'Dijon Mustard',
    category: 'condiments',
    quantity: 200,
    unit: 'g',
    expirationDate: daysFromNow(150),
    location: 'fridge',
    urgency: 'fresh',
    addedDate: daysAgo(45),
  },
]

export const mockRecipes: Recipe[] = [
  {
    id: 'r1',
    title: 'Tomato & Olive Chicken',
    description:
      'Pan-seared chicken breast with cherry tomatoes, kalamata olives, garlic and lemon. Quick to prepare, uses ingredients close to expiry.',
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 2,
    difficulty: 'easy',
    pantryMatchCount: 6,
    totalIngredients: 7,
    usesExpiringItems: true,
    tags: ['chicken', 'mediterranean', 'quick'],
    costLevel: 'medium',
    isSaved: true,
    ingredients: [
      { name: 'Chicken Breast', amount: 600, unit: 'g', inPantry: true },
      { name: 'Cherry Tomatoes', amount: 300, unit: 'g', inPantry: true },
      { name: 'Kalamata Olives', amount: 100, unit: 'g', inPantry: true },
      { name: 'Garlic', amount: 3, unit: 'cloves', inPantry: true },
      { name: 'Lemon', amount: 1, unit: 'pc', inPantry: true },
      { name: 'Unsalted Butter', amount: 30, unit: 'g', inPantry: true },
      { name: 'Fresh Thyme', amount: 4, unit: 'sprigs', inPantry: false, substitution: 'Dried thyme works — use 1 tsp' },
    ],
    steps: [
      { step: 1, instruction: 'Pat chicken breasts dry and season generously with salt and pepper on both sides.' },
      { step: 2, instruction: 'Heat a heavy skillet over medium-high heat. Add butter and let it foam.' },
      { step: 3, instruction: 'Sear chicken for 4–5 minutes per side until golden brown. Remove and rest on a plate.', durationMinutes: 10 },
      { step: 4, instruction: 'In the same pan, add garlic and cook 30 seconds until fragrant.' },
      { step: 5, instruction: 'Add cherry tomatoes and olives. Cook 5 minutes until tomatoes begin to burst.', durationMinutes: 5 },
      { step: 6, instruction: 'Return chicken to pan. Add a squeeze of lemon and simmer 5 more minutes.', durationMinutes: 5 },
      { step: 7, instruction: 'Taste and adjust seasoning. Serve immediately with the pan juices spooned over.' },
    ],
  },
  {
    id: 'r2',
    title: 'Parmesan Risotto',
    description:
      'Classic risotto made with arborio rice, parmesan, and vegetable stock. Finished with cold butter for an exceptionally creamy texture.',
    prepTimeMinutes: 5,
    cookTimeMinutes: 30,
    servings: 4,
    difficulty: 'medium',
    pantryMatchCount: 5,
    totalIngredients: 6,
    usesExpiringItems: false,
    tags: ['italian', 'vegetarian', 'comfort'],
    costLevel: 'low',
    isSaved: false,
    ingredients: [
      { name: 'Arborio Rice', amount: 320, unit: 'g', inPantry: true },
      { name: 'Parmesan Cheese', amount: 80, unit: 'g', inPantry: true },
      { name: 'Vegetable Stock', amount: 1, unit: 'L', inPantry: true },
      { name: 'Unsalted Butter', amount: 60, unit: 'g', inPantry: true },
      { name: 'Garlic', amount: 2, unit: 'cloves', inPantry: true },
      { name: 'Dry White Wine', amount: 100, unit: 'ml', inPantry: false, substitution: 'Extra stock with a splash of white wine vinegar' },
    ],
    steps: [
      { step: 1, instruction: 'Warm stock in a separate saucepan over low heat. Keep it just below a simmer.' },
      { step: 2, instruction: 'Melt half the butter in a wide, heavy pan over medium heat. Add garlic, cook 1 minute.' },
      { step: 3, instruction: 'Add rice and stir to coat in butter. Toast for 2 minutes until edges turn translucent.', durationMinutes: 2 },
      { step: 4, instruction: 'Add wine (or stock substitute) and stir until fully absorbed.' },
      { step: 5, instruction: 'Add warm stock one ladle at a time, stirring constantly. Wait until each ladleful is absorbed before adding the next. Continue for 18–20 minutes.', durationMinutes: 20 },
      { step: 6, instruction: 'Remove from heat. Stir in remaining cold butter and half the parmesan. Season with salt and white pepper.' },
      { step: 7, instruction: 'Serve immediately in warm bowls, topped with remaining parmesan and a crack of black pepper.' },
    ],
  },
  {
    id: 'r3',
    title: 'Pan-Seared Salmon with Lemon Butter',
    description:
      'Simply prepared salmon, skin crisped in a hot pan, finished with a brown butter and lemon sauce. Ready in under 20 minutes.',
    prepTimeMinutes: 5,
    cookTimeMinutes: 12,
    servings: 2,
    difficulty: 'easy',
    pantryMatchCount: 4,
    totalIngredients: 5,
    usesExpiringItems: true,
    tags: ['seafood', 'quick', 'gluten-free'],
    costLevel: 'medium',
    isSaved: true,
    ingredients: [
      { name: 'Salmon Fillet', amount: 400, unit: 'g', inPantry: true },
      { name: 'Unsalted Butter', amount: 40, unit: 'g', inPantry: true },
      { name: 'Lemon', amount: 1, unit: 'pc', inPantry: true },
      { name: 'Garlic', amount: 2, unit: 'cloves', inPantry: true },
      { name: 'Capers', amount: 1, unit: 'tbsp', inPantry: false, substitution: 'Finely chopped olives' },
    ],
    steps: [
      { step: 1, instruction: 'Pat salmon dry. Season flesh side with salt and pepper. Score skin lightly.' },
      { step: 2, instruction: 'Heat a stainless steel pan until very hot. Add a thin layer of neutral oil.' },
      { step: 3, instruction: 'Place salmon skin-side down. Press gently with a spatula for 30 seconds to prevent curling. Cook 4–5 minutes without moving.', durationMinutes: 5 },
      { step: 4, instruction: 'Flip and cook flesh side 1–2 minutes. Remove salmon to rest.', durationMinutes: 2 },
      { step: 5, instruction: 'Reduce heat to medium. Add butter, garlic, and lemon juice. Swirl until butter foams and turns golden.' },
      { step: 6, instruction: 'Spoon sauce over salmon. Serve immediately with seasonal greens.' },
    ],
  },
  {
    id: 'r4',
    title: 'Yoghurt & Tomato Egg Bake',
    description:
      'Spiced tomatoes baked with eggs and finished with cool Greek yoghurt. A complete, satisfying meal built around expiring produce.',
    prepTimeMinutes: 8,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: 'easy',
    pantryMatchCount: 5,
    totalIngredients: 6,
    usesExpiringItems: true,
    tags: ['vegetarian', 'eggs', 'breakfast'],
    costLevel: 'low',
    isSaved: false,
    ingredients: [
      { name: 'Free-Range Eggs', amount: 4, unit: 'pcs', inPantry: true },
      { name: 'Cherry Tomatoes', amount: 250, unit: 'g', inPantry: true },
      { name: 'Greek Yoghurt', amount: 150, unit: 'g', inPantry: true },
      { name: 'Garlic', amount: 2, unit: 'cloves', inPantry: true },
      { name: 'Whole Milk', amount: 50, unit: 'ml', inPantry: true },
      { name: 'Smoked Paprika', amount: 1, unit: 'tsp', inPantry: false, substitution: 'Regular paprika or chili flakes' },
    ],
    steps: [
      { step: 1, instruction: 'Preheat oven to 200°C. Heat an oven-safe skillet over medium heat with a drizzle of oil.' },
      { step: 2, instruction: 'Add garlic and tomatoes. Cook until tomatoes blister and release their juices, about 8 minutes.', durationMinutes: 8 },
      { step: 3, instruction: 'Season with paprika, salt, and pepper. Stir to combine.' },
      { step: 4, instruction: 'Make 4 wells in the tomato mixture. Crack one egg into each well.' },
      { step: 5, instruction: 'Transfer to oven and bake 8–10 minutes until whites are just set and yolks remain runny.', durationMinutes: 10 },
      { step: 6, instruction: 'Remove from oven. Spoon yoghurt over the top and season. Serve directly from the pan.' },
    ],
  },
  {
    id: 'r5',
    title: 'Green Pea & Parmesan Soup',
    description:
      'A bright, silky soup from frozen peas and parmesan, ready in 15 minutes. Clean and clean-flavoured.',
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    servings: 4,
    difficulty: 'easy',
    pantryMatchCount: 4,
    totalIngredients: 5,
    usesExpiringItems: false,
    tags: ['vegetarian', 'quick', 'soup'],
    costLevel: 'low',
    isSaved: false,
    ingredients: [
      { name: 'Frozen Peas', amount: 400, unit: 'g', inPantry: true },
      { name: 'Vegetable Stock', amount: 750, unit: 'ml', inPantry: true },
      { name: 'Parmesan Cheese', amount: 50, unit: 'g', inPantry: true },
      { name: 'Garlic', amount: 2, unit: 'cloves', inPantry: true },
      { name: 'Mint Leaves', amount: 10, unit: 'g', inPantry: false, substitution: 'Basil or flat-leaf parsley' },
    ],
    steps: [
      { step: 1, instruction: 'Bring stock to a boil in a medium saucepan. Add garlic and peas.' },
      { step: 2, instruction: 'Cook peas 3–4 minutes until just tender but still bright green.', durationMinutes: 4 },
      { step: 3, instruction: 'Blend until completely smooth using a hand blender. Add a splash more stock if too thick.' },
      { step: 4, instruction: 'Return to low heat. Stir in parmesan and season with salt and white pepper.' },
      { step: 5, instruction: 'Ladle into bowls. Finish with a few mint leaves, a drizzle of good olive oil, and extra parmesan.' },
    ],
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'expiring_soon',
    title: 'Salmon Fillet expires tomorrow',
    message: 'Use your salmon fillet before it expires. Pan-Seared Salmon with Lemon Butter uses it.',
    itemId: 'p14',
    recipeId: 'r3',
    createdAt: new Date().toISOString(),
    isRead: false,
    daysUntilExpiry: 1,
  },
  {
    id: 'n2',
    type: 'expiring_soon',
    title: 'Whole Milk expires in 2 days',
    message: 'Your whole milk is approaching its best-before date.',
    itemId: 'p1',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    isRead: false,
    daysUntilExpiry: 2,
  },
  {
    id: 'n3',
    type: 'expired',
    title: 'Baby Spinach has expired',
    message: 'Baby spinach expired yesterday. Remove it from your pantry.',
    itemId: 'p6',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    isRead: false,
  },
  {
    id: 'n4',
    type: 'recipe_suggestion',
    title: 'Recipe idea: Tomato & Olive Chicken',
    message: 'Your cherry tomatoes and chicken breast expire in 2–3 days. This recipe uses both.',
    recipeId: 'r1',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    isRead: true,
  },
  {
    id: 'n5',
    type: 'unused_long',
    title: 'Dijon Mustard unused for 45 days',
    message: 'Your Dijon Mustard has been sitting since you added it. Consider using it soon.',
    itemId: 'p18',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isRead: true,
  },
  {
    id: 'n6',
    type: 'expired',
    title: 'Sourdough Bread has expired',
    message: 'Sourdough bread expired 2 days ago. Remove it from your pantry.',
    itemId: 'p17',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isRead: true,
  },
  {
    id: 'n7',
    type: 'expiring_soon',
    title: 'Kalamata Olives expire in 3 days',
    message: 'Use your kalamata olives before they expire. Tomato & Olive Chicken is a good option.',
    itemId: 'p11',
    recipeId: 'r1',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    isRead: true,
    daysUntilExpiry: 3,
  },
]

export const mockBudgetStats: BudgetStats = {
  itemsSavedCount: 14,
  estimatedSavedAmount: 47.2,
  estimatedWastedAmount: 11.8,
  weeklyData: [
    { week: 'Jun 2', saved: 8.4, wasted: 3.2 },
    { week: 'Jun 9', saved: 12.6, wasted: 0 },
    { week: 'Jun 16', saved: 6.8, wasted: 5.4 },
    { week: 'Jun 23', saved: 11.2, wasted: 1.8 },
    { week: 'Jun 30', saved: 8.2, wasted: 1.4 },
  ],
  monthlyTotals: [
    { month: 'Mar', saved: 32, wasted: 18 },
    { month: 'Apr', saved: 41, wasted: 12 },
    { month: 'May', saved: 38, wasted: 15 },
    { month: 'Jun', saved: 47, wasted: 12 },
  ],
}

export const mockUserProfile: UserProfile = {
  id: 'u1',
  name: 'Alex Marchand',
  email: 'alex@example.com',
  householdSize: 2,
  dietaryPreferences: ['Vegetarian-friendly', 'Gluten-free options'],
  notificationDaysAhead: 3,
}
